name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: npm install --legacy-peer-deps --prefer-offline
        timeout-minutes: 5
        
      - name: Build with Next.js
        run: npm run build
        timeout-minutes: 8
        env:
          NODE_ENV: production
          NEXT_TELEMETRY_DISABLED: 1
          
      # Debug output
      - name: List directories
        run: ls -la
        
      - name: Check for out directory
        run: ls -la ./out || echo "Out directory not found"
        
      # Make sure the out directory exists before creating .nojekyll
      - name: Create output directory if it doesn't exist
        run: mkdir -p ./out
        
      - name: Create .nojekyll file
        run: touch ./out/.nojekyll
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
